### ISSUE TITLE
qiongB废物，记得看你爸爸的回复

### ISSUE THREAD

**Issue by CaiWanFeng** [419632131/DJCamera#2]
还有你的微信头像，就TM是个龟儿子

**Comment by 419632131** [comment]
这就破防说脏话了？素质感人啊。还有，以你的智商应该搞不清谁是谁吧？

**Comment by 419632131** [comment]
周末还要看github呢？看来生活过的不怎么样啊，挺辛苦的吧，也是啊，不然咋会卖demo维生呢，太惨了，表示同情
